// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bots-page/AnalyticsHub.tsx": () => import("../components/mockups/bots-page/AnalyticsHub.tsx"),
  "./components/mockups/bots-page/AppStore.tsx": () => import("../components/mockups/bots-page/AppStore.tsx"),
  "./components/mockups/bots-page/CRMProfile.tsx": () => import("../components/mockups/bots-page/CRMProfile.tsx"),
  "./components/mockups/bots-page/IOSSettings.tsx": () => import("../components/mockups/bots-page/IOSSettings.tsx"),
  "./components/mockups/bots-page/NotionStyle.tsx": () => import("../components/mockups/bots-page/NotionStyle.tsx"),
  "./components/mockups/bots-page/PremiumDash.tsx": () => import("../components/mockups/bots-page/PremiumDash.tsx"),
  "./components/mockups/bots-page/ProjectManager.tsx": () => import("../components/mockups/bots-page/ProjectManager.tsx"),
  "./components/mockups/bots-page/SmartHome.tsx": () => import("../components/mockups/bots-page/SmartHome.tsx"),
  "./components/mockups/bots-page/VercelDeploy.tsx": () => import("../components/mockups/bots-page/VercelDeploy.tsx"),
  "./components/mockups/bots-page/WhatsAppStyle.tsx": () => import("../components/mockups/bots-page/WhatsAppStyle.tsx"),
  "./components/mockups/dashboard-layouts/ActivityFeed.tsx": () => import("../components/mockups/dashboard-layouts/ActivityFeed.tsx"),
  "./components/mockups/dashboard-layouts/CardGrid.tsx": () => import("../components/mockups/dashboard-layouts/CardGrid.tsx"),
  "./components/mockups/dashboard-layouts/CommandCenter.tsx": () => import("../components/mockups/dashboard-layouts/CommandCenter.tsx"),
  "./components/mockups/dashboard-layouts/MinimalClean.tsx": () => import("../components/mockups/dashboard-layouts/MinimalClean.tsx"),
  "./components/mockups/dashboard-saas/BotStudio.tsx": () => import("../components/mockups/dashboard-saas/BotStudio.tsx"),
  "./components/mockups/dashboard-saas/ControlPanel.tsx": () => import("../components/mockups/dashboard-saas/ControlPanel.tsx"),
  "./components/mockups/dashboard-saas/HubPlatform.tsx": () => import("../components/mockups/dashboard-saas/HubPlatform.tsx"),
  "./components/mockups/dashboard-saas/Workspace.tsx": () => import("../components/mockups/dashboard-saas/Workspace.tsx")
};
