// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dashboard-layouts/ActivityFeed.tsx": () => import("../components/mockups/dashboard-layouts/ActivityFeed.tsx"),
  "./components/mockups/dashboard-layouts/CardGrid.tsx": () => import("../components/mockups/dashboard-layouts/CardGrid.tsx"),
  "./components/mockups/dashboard-layouts/CommandCenter.tsx": () => import("../components/mockups/dashboard-layouts/CommandCenter.tsx"),
  "./components/mockups/dashboard-layouts/MinimalClean.tsx": () => import("../components/mockups/dashboard-layouts/MinimalClean.tsx")
};
